In [ ]:
#pip install ultralytics

In [1]:
import pyrealsense2 as rs
import numpy as np
import cv2
import ultralytics
from ultralytics import YOLO

In [2]:
model=YOLO("yolov8n-pose.pt")

In [12]:
config=rs.config()
pipeline=rs.pipeline()
#config.enable_stream(rs.stream.depth,640,480,rs.format.z16,30)
config.enable_stream(rs.stream.color,640,480,rs.format.bgr8,30)

In [29]:
pipeline.stop()

In [33]:
pipeline.start(config)
while True:
    frames=pipeline.wait_for_frames()
    color=frames.get_color_frame()
    color_image=np.asanyarray(color.get_data())
    print(color_image)
    res=model(cv2.cvtColor(color_image,cv2.COLOR_BGR2RGB),)
    res_plotted = res[0].plot(boxes=False)
    cv2.namedWindow('RGB FEED', cv2.WINDOW_AUTOSIZE)
    cv2.imshow('RGB FEED', res_plotted)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
pipeline.stop()
cv2.destroyAllWindows()

[[[  4   6   0 255]
  [  3   5   0 255]
  [  4   6   0 255]
  ...
  [  0   6   2 255]
  [  0   8   1 255]
  [  0   8   1 255]]

 [[  0   6   0 255]
  [  0   6   0 255]
  [  1   7   0 255]
  ...
  [  0   6   2 255]
  [  0   7   0 255]
  [  0   8   1 255]]

 [[  1   7   0 255]
  [  1   7   0 255]
  [  1   7   0 255]
  ...
  [  0   7   2 255]
  [  0   8   3 255]
  [  0   8   3 255]]

 ...

 [[  0   2   0 255]
  [  0   2   0 255]
  [  0   2   0 255]
  ...
  [  0   2   1 255]
  [  0   2   1 255]
  [  0   2   1 255]]

 [[  0   2   0 255]
  [  0   2   0 255]
  [  0   2   0 255]
  ...
  [  0   2   1 255]
  [  0   2   1 255]
  [  0   2   1 255]]

 [[  0   2   0 255]
  [  0   2   0 255]
  [  0   2   0 255]
  ...
  [  0   2   1 255]
  [  0   2   1 255]
  [  0   1   0 255]]]


0: 480x640 (no detections), 451.1ms
Speed: 6.8ms preprocess, 451.1ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[[[ 84  99  73 255]
  [ 77  92  66 255]
  [ 85  92  67 255]
  ...
  [ 80 104 131 255]
  [ 68  95 128 255]
  [ 63  90 123 255]]

 [[ 85  98  72 255]
  [ 79  92  66 255]
  [ 84  91  71 255]
  ...
  [ 78 105 129 255]
  [ 70  97 128 255]
  [ 64  91 122 255]]

 [[ 82  94  75 255]
  [ 77  89  70 255]
  [ 86  91  78 255]
  ...
  [ 70 105 127 255]
  [ 69  98 129 255]
  [ 65  94 125 255]]

 ...

 [[ 91  96  92 255]
  [ 95 100  96 255]
  [ 91  98  89 255]
  ...
  [ 14  61 107 255]
  [ 10  58 106 255]
  [ 11  59 107 255]]

 [[ 88  95  91 255]
  [ 91  98  94 255]
  [ 88  94  87 255]
  ...
  [ 16  61 107 255]
  [ 16  64 112 255]
  [ 14  62 110 255]]

 [[ 82  92  87 255]
  [ 82  92  87 255]
  [ 83  94  86 255]
  ...
  [ 14  60 108 255]
  [ 16  62 110 255]
  [ 12  58 106 255]]]


0: 480x640 (no detections), 227.8ms
Speed: 0.0ms preprocess, 227.8ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[[[ 26  78 128 255]
  [ 19  71 121 255]
  [ 43  69 118 255]
  ...
  [ 36  83 129 255]
  [  6  87 132 255]
  [  8  89 134 255]]

 [[ 27  80 127 255]
  [ 19  72 119 255]
  [ 37  70 118 255]
  ...
  [ 38  82 130 255]
  [  8  87 134 255]
  [ 15  94 141 255]]

 [[ 31  79 127 255]
  [ 25  73 121 255]
  [ 35  71 121 255]
  ...
  [ 36  80 128 255]
  [ 13  82 136 255]
  [ 12  81 135 255]]

 ...

 [[ 19  29  24 255]
  [ 16  26  21 255]
  [  7  23  26 255]
  ...
  [ 57  91 141 255]
  [ 52  95 132 255]
  [ 56  99 136 255]]

 [[ 20  27  23 255]
  [ 18  25  21 255]
  [ 11  20  29 255]
  ...
  [ 58  92 142 255]
  [ 55  96 132 255]
  [ 55  96 132 255]]

 [[ 21  26  22 255]
  [ 21  26  22 255]
  [ 19  20  35 255]
  ...
  [ 54  94 141 255]
  [ 55  96 132 255]
  [ 54  95 131 255]]]


0: 480x640 (no detections), 215.9ms
Speed: 1.2ms preprocess, 215.9ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[[[195 229 254 255]
  [193 227 252 255]
  [196 226 249 255]
  ...
  [ 30  39  57 255]
  [ 30  42  57 255]
  [ 32  44  59 255]]

 [[193 229 249 255]
  [193 229 249 255]
  [193 223 246 255]
  ...
  [ 30  37  53 255]
  [ 34  42  56 255]
  [ 36  44  58 255]]

 [[195 232 247 255]
  [196 233 248 255]
  [198 226 248 255]
  ...
  [ 32  38  52 255]
  [ 40  45  56 255]
  [ 40  45  56 255]]

 ...

 [[ 79  90  82 255]
  [ 77  88  80 255]
  [ 76  94  85 255]
  ...
  [ 36  28   7 255]
  [ 36  23   8 255]
  [ 38  25  10 255]]

 [[ 71  89  80 255]
  [ 69  87  78 255]
  [ 66  93  83 255]
  ...
  [ 39  29  13 255]
  [ 30  23  13 255]
  [ 32  25  15 255]]

 [[ 73  88  80 255]
  [ 73  88  80 255]
  [ 61  91  80 255]
  ...
  [ 37  31  17 255]
  [ 29  23  21 255]
  [ 26  20  18 255]]]


0: 480x640 (no detections), 203.6ms
Speed: 0.0ms preprocess, 203.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)



[[[254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]
  ...
  [254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]]

 [[254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]
  ...
  [254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]]

 [[254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]
  ...
  [254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]]

 ...

 [[ 89  92  84 255]
  [ 87  90  82 255]
  [ 97  85  90 255]
  ...
  [ 31  40  31 255]
  [ 32  38  37 255]
  [ 26  32  31 255]]

 [[ 92  93  78 255]
  [ 94  95  80 255]
  [ 97  89  87 255]
  ...
  [ 34  40  33 255]
  [ 34  38  37 255]
  [ 28  32  31 255]]

 [[ 92  93  71 255]
  [ 96  97  75 255]
  [ 99  93  86 255]
  ...
  [ 39  41  35 255]
  [ 36  36  36 255]
  [ 32  32  32 255]]]


0: 480x640 (no detections), 245.1ms
Speed: 2.0ms preprocess, 245.1ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)



[[[202 221 210 255]
  [208 227 216 255]
  [209 228 217 255]
  ...
  [ 85  58  72 255]
  [ 94  53  68 255]
  [ 96  55  70 255]]

 [[202 221 210 255]
  [205 224 213 255]
  [211 226 218 255]
  ...
  [ 88  62  74 255]
  [ 94  59  70 255]
  [ 94  59  70 255]]

 [[205 222 216 255]
  [202 219 213 255]
  [211 223 218 255]
  ...
  [ 93  66  74 255]
  [ 93  60  65 255]
  [ 94  61  66 255]]

 ...

 [[ 69  45  38 255]
  [ 68  44  37 255]
  [ 70  42  39 255]
  ...
  [ 43  47  52 255]
  [ 47  42  51 255]
  [ 50  45  54 255]]

 [[ 67  44  35 255]
  [ 69  46  37 255]
  [ 73  42  28 255]
  ...
  [ 40  46  53 255]
  [ 43  43  53 255]
  [ 44  44  54 255]]

 [[ 70  47  29 255]
  [ 77  54  36 255]
  [ 78  53  28 255]
  ...
  [ 38  42  47 255]
  [ 46  43  52 255]
  [ 46  43  52 255]]]


0: 480x640 4 persons, 215.4ms
Speed: 3.0ms preprocess, 215.4ms inference, 15.9ms postprocess per image at shape (1, 3, 480, 640)



[[[177 189 197 255]
  [176 188 196 255]
  [178 190 192 255]
  ...
  [ 73  57  40 255]
  [ 80  57  32 255]
  [ 80  57  32 255]]

 [[177 190 196 255]
  [175 188 194 255]
  [181 193 195 255]
  ...
  [ 73  57  40 255]
  [ 79  59  32 255]
  [ 78  58  31 255]]

 [[177 192 198 255]
  [179 194 200 255]
  [184 195 199 255]
  ...
  [ 76  53  42 255]
  [ 79  57  37 255]
  [ 77  55  35 255]]

 ...

 [[126 131  90 255]
  [140 145 104 255]
  [165 152 119 255]
  ...
  [ 51  47  58 255]
  [ 53  48  57 255]
  [ 49  44  53 255]]

 [[117 125  82 255]
  [124 132  89 255]
  [146 133 106 255]
  ...
  [ 48  51  54 255]
  [ 48  48  49 255]
  [ 44  44  45 255]]

 [[111 113  75 255]
  [113 115  77 255]
  [138 114  94 255]
  ...
  [ 49  53  52 255]
  [ 47  49  43 255]
  [ 43  45  39 255]]]


0: 480x640 4 persons, 188.7ms
Speed: 0.0ms preprocess, 188.7ms inference, 15.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 4 persons, 1 chair, 1 laptop, 174.1ms


[[[152 167 181 255]
  [154 169 183 255]
  [161 171 191 255]
  ...
  [ 94  55  51 255]
  [102  63  52 255]
  [ 98  59  48 255]]

 [[156 172 184 255]
  [155 171 183 255]
  [161 172 190 255]
  ...
  [ 94  59  50 255]
  [ 98  64  52 255]
  [ 94  60  48 255]]

 [[158 173 187 255]
  [156 171 185 255]
  [158 170 185 255]
  ...
  [ 91  60  46 255]
  [ 94  62  50 255]
  [ 89  57  45 255]]

 ...

 [[ 30  16  26 255]
  [ 33  19  29 255]
  [ 30  15  34 255]
  ...
  [ 95  76  87 255]
  [ 95  93  99 255]
  [ 97  95 101 255]]

 [[ 32  18  28 255]
  [ 33  19  29 255]
  [ 28   9  40 255]
  ...
  [100  82  90 255]
  [ 99  95 101 255]
  [102  98 104 255]]

 [[ 30  16  38 255]
  [ 30  16  38 255]
  [ 26  13  46 255]
  ...
  [101  84  90 255]
  [101  97  98 255]
  [101  97  98 255]]]


Speed: 0.0ms preprocess, 174.1ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[[[144 145 168 255]
  [146 147 170 255]
  [144 149 160 255]
  ...
  [106  75  56 255]
  [108  63  64 255]
  [108  63  64 255]]

 [[137 146 171 255]
  [138 147 172 255]
  [138 148 163 255]
  ...
  [106  77  51 255]
  [104  64  58 255]
  [105  65  59 255]]

 [[132 149 170 255]
  [131 148 169 255]
  [134 149 163 255]
  ...
  [103  72  44 255]
  [105  67  59 255]
  [103  65  57 255]]

 ...

 [[ 18  14  27 255]
  [ 18  14  27 255]
  [ 22  12  22 255]
  ...
  [ 45  28   7 255]
  [ 42  29   2 255]
  [ 44  31   4 255]]

 [[ 18  13  29 255]
  [ 20  15  31 255]
  [ 21  15  26 255]
  ...
  [ 46  28   9 255]
  [ 47  29   3 255]
  [ 50  32   6 255]]

 [[ 18  13  29 255]
  [ 20  15  31 255]
  [ 20  16  27 255]
  ...
  [ 49  27  13 255]
  [ 51  28  10 255]
  [ 52  29  11 255]]]


0: 480x640 5 persons, 1 chair, 179.0ms
Speed: 8.0ms preprocess, 179.0ms inference, 18.2ms postprocess per image at shape (1, 3, 480, 640)



[[[124 134 149 255]
  [123 133 148 255]
  [121 131 151 255]
  ...
  [107  65  57 255]
  [ 93  66  60 255]
  [ 91  64  58 255]]

 [[124 134 149 255]
  [123 133 148 255]
  [123 132 150 255]
  ...
  [105  67  54 255]
  [ 97  67  57 255]
  [ 94  64  54 255]]

 [[123 133 148 255]
  [122 132 147 255]
  [121 133 148 255]
  ...
  [101  69  52 255]
  [ 99  68  54 255]
  [ 96  65  51 255]]

 ...

 [[ 12  14  19 255]
  [ 10  12  17 255]
  [ 18  15  19 255]
  ...
  [ 31  26  21 255]
  [ 32  25  20 255]
  [ 31  24  19 255]]

 [[ 15  12  21 255]
  [ 16  13  22 255]
  [ 18  13  22 255]
  ...
  [ 33  27  20 255]
  [ 32  25  20 255]
  [ 32  25  20 255]]

 [[ 18  13  22 255]
  [ 18  13  22 255]
  [ 18  12  23 255]
  ...
  [ 35  27  20 255]
  [ 35  26  21 255]
  [ 35  26  21 255]]]


0: 480x640 4 persons, 1 chair, 1 tv, 189.8ms
Speed: 0.0ms preprocess, 189.8ms inference, 23.8ms postprocess per image at shape (1, 3, 480, 640)



[[[122 118 129 255]
  [121 117 128 255]
  [126 114 124 255]
  ...
  [ 38  25  19 255]
  [ 38  24  26 255]
  [ 36  22  24 255]]

 [[119 119 131 255]
  [118 118 130 255]
  [122 114 125 255]
  ...
  [ 38  25  19 255]
  [ 37  24  23 255]
  [ 36  23  22 255]]

 [[117 119 131 255]
  [116 118 130 255]
  [118 114 125 255]
  ...
  [ 38  25  19 255]
  [ 37  24  23 255]
  [ 36  23  22 255]]

 ...

 [[  8  10  20 255]
  [ 10  12  22 255]
  [ 10  13  21 255]
  ...
  [ 15  17  22 255]
  [ 13  17  22 255]
  [ 14  18  23 255]]

 [[  8  10  20 255]
  [ 10  12  22 255]
  [ 10  12  22 255]
  ...
  [ 15  17  22 255]
  [ 12  17  20 255]
  [ 13  18  21 255]]

 [[  8  10  20 255]
  [ 10  12  22 255]
  [ 10  12  22 255]
  ...
  [ 13  17  22 255]
  [ 14  17  20 255]
  [ 14  17  20 255]]]


0: 480x640 3 persons, 1 cat, 210.1ms
Speed: 0.0ms preprocess, 210.1ms inference, 12.2ms postprocess per image at shape (1, 3, 480, 640)



[[[117 119 129 255]
  [118 120 130 255]
  [117 119 129 255]
  ...
  [ 24  15  16 255]
  [ 29  19  10 255]
  [ 28  18   9 255]]

 [[116 118 128 255]
  [117 119 129 255]
  [117 120 128 255]
  ...
  [ 24  15  16 255]
  [ 29  18  12 255]
  [ 28  17  11 255]]

 [[116 118 128 255]
  [117 119 129 255]
  [117 119 129 255]
  ...
  [ 21  14  16 255]
  [ 27  18  13 255]
  [ 26  17  12 255]]

 ...

 [[ 19  21  33 255]
  [ 19  21  33 255]
  [ 23  23  33 255]
  ...
  [ 10  14  28 255]
  [  8  14  28 255]
  [  8  14  28 255]]

 [[ 17  17  34 255]
  [ 17  17  34 255]
  [ 21  21  31 255]
  ...
  [ 10  14  28 255]
  [  8  14  28 255]
  [  7  13  27 255]]

 [[ 17  15  32 255]
  [ 17  15  32 255]
  [ 26  22  28 255]
  ...
  [  9  13  27 255]
  [  8  14  28 255]
  [  8  14  28 255]]]


0: 480x640 5 persons, 221.9ms
Speed: 0.0ms preprocess, 221.9ms inference, 16.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 4 persons, 184.0ms


[[[117 120 136 255]
  [118 121 137 255]
  [117 118 133 255]
  ...
  [ 21  10  22 255]
  [ 10  18  25 255]
  [  8  16  23 255]]

 [[117 120 136 255]
  [118 121 137 255]
  [116 120 134 255]
  ...
  [ 21  10  22 255]
  [ 12  18  25 255]
  [ 10  16  23 255]]

 [[118 122 136 255]
  [119 123 137 255]
  [119 123 137 255]
  ...
  [ 21  10  22 255]
  [ 14  15  23 255]
  [ 14  15  23 255]]

 ...

 [[ 15  15  32 255]
  [ 15  15  32 255]
  [ 25  19  30 255]
  ...
  [ 10  17  28 255]
  [ 13  15  25 255]
  [ 12  14  24 255]]

 [[ 15  15  32 255]
  [ 15  15  32 255]
  [ 31  22  29 255]
  ...
  [ 10  17  28 255]
  [ 12  14  26 255]
  [ 14  16  28 255]]

 [[ 16  15  30 255]
  [ 19  18  33 255]
  [ 37  26  28 255]
  ...
  [ 11  16  25 255]
  [ 12  14  24 255]
  [ 14  16  26 255]]]


Speed: 0.0ms preprocess, 184.0ms inference, 6.5ms postprocess per image at shape (1, 3, 480, 640)



[[[121 126 137 255]
  [123 128 139 255]
  [128 128 140 255]
  ...
  [ 24  16  21 255]
  [ 17  14  18 255]
  [ 15  12  16 255]]

 [[119 124 133 255]
  [123 128 137 255]
  [126 128 138 255]
  ...
  [ 24  16  21 255]
  [ 17  14  18 255]
  [ 15  12  16 255]]

 [[118 123 132 255]
  [122 127 136 255]
  [124 129 138 255]
  ...
  [ 24  16  21 255]
  [ 17  14  18 255]
  [ 17  14  18 255]]

 ...

 [[ 96  72  45 255]
  [ 95  71  44 255]
  [ 57  41  29 255]
  ...
  [  9  15  22 255]
  [  8  14  21 255]
  [  9  15  22 255]]

 [[ 77  61  44 255]
  [ 63  47  30 255]
  [ 45  34  28 255]
  ...
  [ 11  14  22 255]
  [ 10  14  19 255]
  [ 12  16  21 255]]

 [[ 61  50  39 255]
  [ 48  37  26 255]
  [ 35  30  25 255]
  ...
  [ 13  14  22 255]
  [ 12  14  19 255]
  [ 13  15  20 255]]]


0: 480x640 5 persons, 191.2ms
Speed: 0.0ms preprocess, 191.2ms inference, 22.1ms postprocess per image at shape (1, 3, 480, 640)



[[[137 136 140 255]
  [137 136 140 255]
  [138 137 141 255]
  ...
  [ 15  15  15 255]
  [  8  14  13 255]
  [  8  14  13 255]]

 [[137 136 140 255]
  [137 136 140 255]
  [138 137 141 255]
  ...
  [ 15  16  13 255]
  [  8  15  11 255]
  [  7  14  10 255]]

 [[138 135 139 255]
  [138 135 139 255]
  [140 138 139 255]
  ...
  [ 13  14  11 255]
  [  7  14  10 255]
  [  7  14  10 255]]

 ...

 [[ 83  50  27 255]
  [ 82  49  26 255]
  [ 79  48  27 255]
  ...
  [  8  16  23 255]
  [  7  14  23 255]
  [  8  15  24 255]]

 [[ 81  50  31 255]
  [ 79  48  29 255]
  [ 73  43  26 255]
  ...
  [  7  15  22 255]
  [  7  14  23 255]
  [  7  14  23 255]]

 [[ 78  47  33 255]
  [ 76  45  31 255]
  [ 70  42  27 255]
  ...
  [  7  15  22 255]
  [  7  14  23 255]
  [  7  14  23 255]]]


0: 480x640 4 persons, 1 laptop, 221.6ms
Speed: 0.0ms preprocess, 221.6ms inference, 23.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 3 persons, 190.1ms


[[[145 135 145 255]
  [144 134 144 255]
  [148 134 144 255]
  ...
  [ 25  15  25 255]
  [ 19  15  26 255]
  [ 18  14  25 255]]

 [[145 137 142 255]
  [145 137 142 255]
  [144 135 142 255]
  ...
  [ 24  14  24 255]
  [ 19  16  25 255]
  [ 18  15  24 255]]

 [[144 137 139 255]
  [146 139 141 255]
  [146 138 143 255]
  ...
  [ 22  15  24 255]
  [ 18  16  22 255]
  [ 17  15  21 255]]

 ...

 [[ 98  66  29 255]
  [ 91  59  22 255]
  [ 84  52  22 255]
  ...
  [ 13  16  19 255]
  [ 11  15  20 255]
  [ 12  16  21 255]]

 [[ 95  65  33 255]
  [ 89  59  27 255]
  [ 85  53  23 255]
  ...
  [ 11  16  19 255]
  [ 11  15  20 255]
  [ 11  15  20 255]]

 [[ 91  65  36 255]
  [ 87  61  32 255]
  [ 84  54  24 255]
  ...
  [ 11  16  19 255]
  [ 11  15  20 255]
  [ 11  15  20 255]]]


Speed: 0.0ms preprocess, 190.1ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[[[147 146 143 255]
  [148 147 144 255]
  [147 144 141 255]
  ...
  [ 27  13  30 255]
  [ 19  15  21 255]
  [ 18  14  20 255]]

 [[146 145 142 255]
  [146 145 142 255]
  [147 144 141 255]
  ...
  [ 25  13  30 255]
  [ 19  14  23 255]
  [ 18  13  22 255]]

 [[148 144 144 255]
  [147 143 143 255]
  [147 143 144 255]
  ...
  [ 25  14  28 255]
  [ 21  15  21 255]
  [ 20  14  20 255]]

 ...

 [[ 68  42  20 255]
  [ 70  44  22 255]
  [ 65  40  27 255]
  ...
  [ 11  15  20 255]
  [  9  18  22 255]
  [ 10  19  23 255]]

 [[ 66  40  20 255]
  [ 67  41  21 255]
  [ 62  40  26 255]
  ...
  [ 13  16  19 255]
  [ 11  18  22 255]
  [ 12  19  23 255]]

 [[ 66  38  23 255]
  [ 63  35  20 255]
  [ 60  37  26 255]
  ...
  [ 17  16  20 255]
  [ 13  17  22 255]
  [ 13  17  22 255]]]


0: 480x640 4 persons, 204.7ms
Speed: 16.4ms preprocess, 204.7ms inference, 15.6ms postprocess per image at shape (1, 3, 480, 640)



[[[151 149 155 255]
  [149 147 153 255]
  [150 148 154 255]
  ...
  [ 60  37  41 255]
  [ 58  30  35 255]
  [ 60  32  37 255]]

 [[153 149 155 255]
  [151 147 153 255]
  [151 149 155 255]
  ...
  [ 57  36  40 255]
  [ 56  30  35 255]
  [ 56  30  35 255]]

 [[153 149 155 255]
  [153 149 155 255]
  [153 149 155 255]
  ...
  [ 52  36  39 255]
  [ 52  31  35 255]
  [ 52  31  35 255]]

 ...

 [[ 20  17  21 255]
  [ 21  18  22 255]
  [ 19  16  25 255]
  ...
  [ 11  15  20 255]
  [ 10  14  19 255]
  [ 12  16  21 255]]

 [[ 20  16  22 255]
  [ 21  17  23 255]
  [ 19  15  26 255]
  ...
  [ 12  14  19 255]
  [ 12  14  19 255]
  [ 14  16  21 255]]

 [[ 21  17  23 255]
  [ 20  16  22 255]
  [ 19  15  26 255]
  ...
  [ 13  15  20 255]
  [ 12  14  19 255]
  [ 14  16  21 255]]]


0: 480x640 4 persons, 1 laptop, 211.8ms
Speed: 0.0ms preprocess, 211.8ms inference, 9.1ms postprocess per image at shape (1, 3, 480, 640)



[[[153 150 147 255]
  [154 151 148 255]
  [154 151 148 255]
  ...
  [ 40  29  41 255]
  [ 55  38  49 255]
  [ 65  48  59 255]]

 [[155 149 147 255]
  [157 151 149 255]
  [156 150 148 255]
  ...
  [ 42  32  42 255]
  [ 55  38  49 255]
  [ 65  48  59 255]]

 [[158 150 148 255]
  [160 152 150 255]
  [157 151 149 255]
  ...
  [ 44  34  44 255]
  [ 54  39  51 255]
  [ 63  48  60 255]]

 ...

 [[ 17  16  20 255]
  [ 17  16  20 255]
  [ 16  15  19 255]
  ...
  [ 15  12  21 255]
  [ 12  14  19 255]
  [ 12  14  19 255]]

 [[ 16  15  19 255]
  [ 16  15  19 255]
  [ 16  15  19 255]
  ...
  [ 12  14  19 255]
  [ 12  14  19 255]
  [ 13  15  20 255]]

 [[ 13  16  19 255]
  [ 12  15  18 255]
  [ 16  16  17 255]
  ...
  [ 12  14  19 255]
  [ 12  14  19 255]
  [ 12  14  19 255]]]


0: 480x640 4 persons, 1 laptop, 209.8ms
Speed: 0.0ms preprocess, 209.8ms inference, 10.8ms postprocess per image at shape (1, 3, 480, 640)



[[[162 149 148 255]
  [162 149 148 255]
  [161 152 147 255]
  ...
  [ 79  88  99 255]
  [ 82  88 107 255]
  [ 79  85 104 255]]

 [[162 152 150 255]
  [160 150 148 255]
  [160 150 148 255]
  ...
  [ 79  88  97 255]
  [ 82  89 105 255]
  [ 83  90 106 255]]

 [[162 152 150 255]
  [160 150 148 255]
  [161 151 149 255]
  ...
  [ 80  90  97 255]
  [ 83  91 105 255]
  [ 83  91 105 255]]

 ...

 [[ 18  17  14 255]
  [ 15  14  11 255]
  [ 14  14   8 255]
  ...
  [ 13  12  16 255]
  [ 13  13  14 255]
  [ 11  11  12 255]]

 [[ 17  15  15 255]
  [ 14  12  12 255]
  [ 14  13  10 255]
  ...
  [ 10  13  16 255]
  [ 12  11  15 255]
  [ 11  10  14 255]]

 [[ 15  12  16 255]
  [ 13  10  14 255]
  [ 13  11  11 255]
  ...
  [ 12  15  18 255]
  [  9  12  15 255]
  [  8  11  14 255]]]


0: 480x640 4 persons, 1 laptop, 186.9ms
Speed: 2.8ms preprocess, 186.9ms inference, 15.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 4 persons, 190.8ms


[[[165 149 152 255]
  [166 150 153 255]
  [165 150 156 255]
  ...
  [ 93  89 111 255]
  [ 90  86 110 255]
  [ 91  87 111 255]]

 [[163 149 151 255]
  [164 150 152 255]
  [163 152 154 255]
  ...
  [ 91  90 110 255]
  [ 88  87 107 255]
  [ 89  88 108 255]]

 [[163 152 153 255]
  [163 152 153 255]
  [164 153 154 255]
  ...
  [ 94  92 109 255]
  [ 92  91 106 255]
  [ 92  91 106 255]]

 ...

 [[ 10   9  13 255]
  [  9   8  12 255]
  [ 13   9  10 255]
  ...
  [ 11  13  23 255]
  [ 10  12  24 255]
  [ 10  12  24 255]]

 [[  9   8  12 255]
  [  9   8  12 255]
  [ 15   8  10 255]
  ...
  [ 11  13  23 255]
  [ 10  11  26 255]
  [  8   9  24 255]]

 [[  9   8  12 255]
  [  9   8  12 255]
  [ 16   7   9 255]
  ...
  [  9  14  23 255]
  [  9  13  27 255]
  [  6  10  24 255]]]


Speed: 0.0ms preprocess, 190.8ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[[[169 163 156 255]
  [166 160 153 255]
  [168 160 153 255]
  ...
  [106 101 110 255]
  [106  98 109 255]
  [106  98 109 255]]

 [[169 163 156 255]
  [166 160 153 255]
  [169 161 154 255]
  ...
  [104 100 111 255]
  [103  97 108 255]
  [104  98 109 255]]

 [[170 162 155 255]
  [169 161 154 255]
  [169 162 152 255]
  ...
  [103  99 112 255]
  [101  97 110 255]
  [101  97 110 255]]

 ...

 [[  9   8  12 255]
  [  9   8  12 255]
  [  6  10  10 255]
  ...
  [  9  14  23 255]
  [ 10  15  26 255]
  [ 10  15  26 255]]

 [[  6   9  12 255]
  [  6   9  12 255]
  [  6  10   9 255]
  ...
  [ 10  12  22 255]
  [  9  14  23 255]
  [  9  14  23 255]]

 [[  6   9  12 255]
  [  6   9  12 255]
  [  6  10   9 255]
  ...
  [  8  11  19 255]
  [ 11  13  23 255]
  [ 11  13  23 255]]]


0: 480x640 3 persons, 206.2ms
Speed: 0.0ms preprocess, 206.2ms inference, 5.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 2 persons, 174.0ms


[[[172 158 161 255]
  [174 160 163 255]
  [177 163 165 255]
  ...
  [104 104 114 255]
  [ 96 100 114 255]
  [ 95  99 113 255]]

 [[170 159 160 255]
  [172 161 162 255]
  [177 163 165 255]
  ...
  [102 104 114 255]
  [ 96 101 112 255]
  [ 95 100 111 255]]

 [[172 158 160 255]
  [173 159 161 255]
  [176 163 162 255]
  ...
  [102 105 113 255]
  [100 105 116 255]
  [ 97 102 113 255]]

 ...

 [[ 12  10  10 255]
  [ 11   9   9 255]
  [ 10   9   6 255]
  ...
  [ 10  12  22 255]
  [ 12  15  23 255]
  [ 12  15  23 255]]

 [[ 11  11  12 255]
  [ 10  10  11 255]
  [ 10   9   6 255]
  ...
  [ 10  12  22 255]
  [ 11  14  22 255]
  [ 12  15  23 255]]

 [[  6  11  14 255]
  [  5  10  13 255]
  [ 10   9   6 255]
  ...
  [ 10  12  24 255]
  [ 12  14  24 255]
  [ 12  14  24 255]]]


Speed: 8.0ms preprocess, 174.0ms inference, 18.0ms postprocess per image at shape (1, 3, 480, 640)



[[[174 166 164 255]
  [174 166 164 255]
  [170 163 158 255]
  ...
  [114 103 105 255]
  [109 104 108 255]
  [108 103 107 255]]

 [[180 165 164 255]
  [178 163 162 255]
  [172 163 158 255]
  ...
  [110 103 105 255]
  [109 104 108 255]
  [109 104 108 255]]

 [[178 163 162 255]
  [178 163 162 255]
  [176 161 160 255]
  ...
  [108 103 107 255]
  [107 104 108 255]
  [109 106 110 255]]

 ...

 [[ 10  12  17 255]
  [  9  11  16 255]
  [  8  12  12 255]
  ...
  [ 14  15  23 255]
  [ 12  13  21 255]
  [ 13  14  22 255]]

 [[ 10  11  19 255]
  [  9  10  18 255]
  [  8  11  14 255]
  ...
  [ 13  14  22 255]
  [ 12  12  22 255]
  [ 13  13  23 255]]

 [[ 10  13  21 255]
  [  7  10  18 255]
  [ 10   9  13 255]
  ...
  [ 13  14  22 255]
  [ 10  12  24 255]
  [ 10  12  24 255]]]


0: 480x640 3 persons, 203.1ms
Speed: 0.0ms preprocess, 203.1ms inference, 15.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 3 persons, 186.6ms


[[[176 165 159 255]
  [172 161 155 255]
  [171 162 151 255]
  ...
  [107 103 109 255]
  [108 101 110 255]
  [107 100 109 255]]

 [[177 166 160 255]
  [178 167 161 255]
  [172 162 153 255]
  ...
  [101 103 108 255]
  [104 101 110 255]
  [102  99 108 255]]

 [[177 167 158 255]
  [179 169 160 255]
  [177 167 158 255]
  ...
  [101 102 110 255]
  [101 102 110 255]
  [100 101 109 255]]

 ...

 [[ 18   7  14 255]
  [ 18   7  14 255]
  [ 15   5  15 255]
  ...
  [ 16  11  15 255]
  [ 14  10  16 255]
  [ 13   9  15 255]]

 [[ 16   7  14 255]
  [ 16   7  14 255]
  [ 13   6  15 255]
  ...
  [ 18  10  15 255]
  [ 14  10  16 255]
  [ 13   9  15 255]]

 [[ 14   8  14 255]
  [ 15   9  15 255]
  [ 12   6  17 255]
  ...
  [ 16  11  15 255]
  [ 14  10  16 255]
  [ 13   9  15 255]]]


Speed: 0.0ms preprocess, 186.6ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[[[186 170 158 255]
  [184 168 156 255]
  [184 167 159 255]
  ...
  [109 105 111 255]
  [100 100 112 255]
  [107 107 119 255]]

 [[186 170 158 255]
  [184 168 156 255]
  [184 168 158 255]
  ...
  [107 105 111 255]
  [100 100 112 255]
  [107 107 119 255]]

 [[184 169 161 255]
  [181 166 158 255]
  [182 167 159 255]
  ...
  [109 106 115 255]
  [100 102 112 255]
  [104 106 116 255]]

 ...

 [[ 13  10  14 255]
  [ 11   8  12 255]
  [ 11   8  12 255]
  ...
  [ 15  13  19 255]
  [ 17  14  23 255]
  [ 16  13  22 255]]

 [[ 12   9  13 255]
  [ 10   7  11 255]
  [  8   7  11 255]
  ...
  [ 15  13  19 255]
  [ 16  13  22 255]
  [ 17  14  23 255]]

 [[ 10   9  13 255]
  [  8   7  11 255]
  [  8   8   9 255]
  ...
  [ 10  12  17 255]
  [ 15  13  19 255]
  [ 16  14  20 255]]]


0: 480x640 4 persons, 1 chair, 1 laptop, 188.0ms
Speed: 0.0ms preprocess, 188.0ms inference, 24.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 2 persons, 1 chair, 178.6ms


[[[185 173 164 255]
  [182 170 161 255]
  [184 169 161 255]
  ...
  [102 100 122 255]
  [100 105 116 255]
  [ 96 101 112 255]]

 [[181 171 162 255]
  [180 170 161 255]
  [182 171 160 255]
  ...
  [101 103 122 255]
  [100 104 118 255]
  [ 95  99 113 255]]

 [[180 170 161 255]
  [179 169 160 255]
  [181 170 159 255]
  ...
  [102 105 121 255]
  [100 104 118 255]
  [ 95  99 113 255]]

 ...

 [[ 11   8  12 255]
  [ 12   9  13 255]
  [ 13   9  10 255]
  ...
  [ 13  11  17 255]
  [  9  10  18 255]
  [  9  10  18 255]]

 [[ 13   9  10 255]
  [ 14  10  11 255]
  [ 14  10  11 255]
  ...
  [ 13  11  17 255]
  [  9  10  18 255]
  [ 10  11  19 255]]

 [[ 13   9  10 255]
  [ 13   9  10 255]
  [ 14  10  11 255]
  ...
  [ 13  11  17 255]
  [  9  10  18 255]
  [ 10  11  19 255]]]


Speed: 0.0ms preprocess, 178.6ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 3 persons, 173.3ms
Speed: 0.0ms preprocess, 173.3ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)


[[[184 170 160 255]
  [183 169 159 255]
  [183 172 159 255]
  ...
  [104 105 113 255]
  [102 104 116 255]
  [104 106 118 255]]

 [[182 171 160 255]
  [181 170 159 255]
  [185 174 161 255]
  ...
  [104 106 111 255]
  [104 104 114 255]
  [105 105 115 255]]

 [[182 170 161 255]
  [182 170 161 255]
  [183 171 162 255]
  ...
  [104 107 110 255]
  [102 104 109 255]
  [104 106 111 255]]

 ...

 [[ 10   8   9 255]
  [  8   6   7 255]
  [  8   8   9 255]
  ...
  [  8  11  19 255]
  [ 12  14  19 255]
  [ 12  14  19 255]]

 [[ 11   9   9 255]
  [  8   6   6 255]
  [ 10   8   9 255]
  ...
  [ 10  12  17 255]
  [ 10  12  17 255]
  [ 12  14  19 255]]

 [[ 12   8   8 255]
  [ 12   8   8 255]
  [ 14  10  10 255]
  ...
  [ 10  12  17 255]
  [ 10  12  17 255]
  [ 12  14  19 255]]]



0: 480x640 4 persons, 191.3ms


[[[180 169 163 255]
  [179 168 162 255]
  [175 169 162 255]
  ...
  [103 106 114 255]
  [104 105 113 255]
  [105 106 114 255]]

 [[178 171 161 255]
  [178 171 161 255]
  [176 170 163 255]
  ...
  [103 105 115 255]
  [102 103 111 255]
  [102 103 111 255]]

 [[181 170 164 255]
  [179 168 162 255]
  [177 169 162 255]
  ...
  [ 98 100 110 255]
  [ 99 101 111 255]
  [ 98 100 110 255]]

 ...

 [[ 15   8   9 255]
  [ 12   5   6 255]
  [ 12   5   6 255]
  ...
  [ 18  14  20 255]
  [ 19  13  19 255]
  [ 19  13  19 255]]

 [[ 15   8   9 255]
  [ 12   5   6 255]
  [ 14   7   8 255]
  ...
  [ 16  13  22 255]
  [ 17  12  21 255]
  [ 18  13  22 255]]

 [[ 13   9   9 255]
  [ 12   8   8 255]
  [ 17   8   9 255]
  ...
  [ 13  14  22 255]
  [ 15  11  22 255]
  [ 16  12  23 255]]]


Speed: 0.0ms preprocess, 191.3ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[[[178 160 160 255]
  [177 159 159 255]
  [176 161 160 255]
  ...
  [103  95 113 255]
  [105  99 110 255]
  [110 104 115 255]]

 [[178 163 162 255]
  [176 161 160 255]
  [176 161 160 255]
  ...
  [101  97 110 255]
  [105  99 110 255]
  [110 104 115 255]]

 [[176 163 162 255]
  [173 160 159 255]
  [173 160 159 255]
  ...
  [101 101 111 255]
  [104 100 111 255]
  [108 104 115 255]]

 ...

 [[ 14  12  13 255]
  [ 12  10  11 255]
  [ 10   7  11 255]
  ...
  [ 13  11  17 255]
  [ 12  14  19 255]
  [ 12  14  19 255]]

 [[ 22  18  19 255]
  [ 17  13  14 255]
  [ 14  10  11 255]
  ...
  [ 12  10  16 255]
  [ 10  11  19 255]
  [ 12  13  21 255]]

 [[ 24  19  23 255]
  [ 22  17  21 255]
  [ 17  13  13 255]
  ...
  [ 12  11  15 255]
  [  9  11  16 255]
  [ 10  12  17 255]]]


0: 480x640 1 person, 1 dog, 190.5ms
Speed: 0.0ms preprocess, 190.5ms inference, 15.8ms postprocess per image at shape (1, 3, 480, 640)



[[[177 162 154 255]
  [176 161 153 255]
  [175 162 156 255]
  ...
  [115 106 113 255]
  [116 109 118 255]
  [118 111 120 255]]

 [[177 161 156 255]
  [177 161 156 255]
  [176 163 157 255]
  ...
  [112 107 111 255]
  [115 109 115 255]
  [118 112 118 255]]

 [[175 162 156 255]
  [175 162 156 255]
  [176 163 157 255]
  ...
  [106 103 107 255]
  [111 106 110 255]
  [115 110 114 255]]

 ...

 [[ 13  11  11 255]
  [ 13  11  11 255]
  [ 15  11  11 255]
  ...
  [ 16  14  20 255]
  [ 13  11  17 255]
  [ 15  13  19 255]]

 [[ 14  12  12 255]
  [ 13  11  11 255]
  [ 15  11  11 255]
  ...
  [ 15  13  19 255]
  [ 12   9  18 255]
  [ 13  10  19 255]]

 [[ 15  11  11 255]
  [ 14  10  10 255]
  [ 16  13  10 255]
  ...
  [ 13  11  17 255]
  [ 12  10  16 255]
  [ 13  11  17 255]]]


0: 480x640 2 persons, 198.4ms
Speed: 0.0ms preprocess, 198.4ms inference, 6.5ms postprocess per image at shape (1, 3, 480, 640)



[[[170 157 156 255]
  [171 158 157 255]
  [169 160 155 255]
  ...
  [109 102 118 255]
  [109 103 121 255]
  [111 105 123 255]]

 [[168 159 154 255]
  [169 160 155 255]
  [169 160 155 255]
  ...
  [108 104 117 255]
  [109 105 118 255]
  [111 107 120 255]]

 [[168 158 156 255]
  [169 159 157 255]
  [169 159 157 255]
  ...
  [110 104 115 255]
  [109 105 116 255]
  [110 106 117 255]]

 ...

 [[ 26  19  21 255]
  [ 26  19  21 255]
  [ 26  20  26 255]
  ...
  [  9  13  13 255]
  [ 10  14  14 255]
  [ 10  14  14 255]]

 [[ 26  19  21 255]
  [ 26  19  21 255]
  [ 24  18  24 255]
  ...
  [ 12  12  13 255]
  [ 13  13  14 255]
  [ 13  13  14 255]]

 [[ 24  18  24 255]
  [ 24  18  24 255]
  [ 24  18  24 255]
  ...
  [ 12  12  13 255]
  [ 13  12  16 255]
  [ 13  12  16 255]]]


0: 480x640 2 persons, 1 chair, 1 laptop, 190.7ms
Speed: 15.8ms preprocess, 190.7ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 2 persons, 1 chair, 1 laptop, 182.5ms


[[[176 164 160 255]
  [176 164 160 255]
  [171 159 164 255]
  ...
  [111 110 114 255]
  [112 105 126 255]
  [109 102 123 255]]

 [[174 166 159 255]
  [172 164 157 255]
  [171 160 162 255]
  ...
  [110 109 113 255]
  [109 103 121 255]
  [108 102 120 255]]

 [[170 164 157 255]
  [170 164 157 255]
  [169 161 159 255]
  ...
  [109 108 112 255]
  [105 101 112 255]
  [107 103 114 255]]

 ...

 [[ 26  17  24 255]
  [ 29  20  27 255]
  [ 27  23  24 255]
  ...
  [ 12  14  19 255]
  [ 12  12  22 255]
  [ 13  13  23 255]]

 [[ 26  16  26 255]
  [ 29  19  29 255]
  [ 27  22  26 255]
  ...
  [ 10  15  18 255]
  [ 10  12  24 255]
  [ 12  14  26 255]]

 [[ 26  16  26 255]
  [ 29  19  29 255]
  [ 29  21  26 255]
  ...
  [ 11  17  17 255]
  [ 10  12  24 255]
  [ 12  14  26 255]]]


Speed: 0.0ms preprocess, 182.5ms inference, 9.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 2 persons, 1 chair, 1 laptop, 175.1ms


[[[164 159 163 255]
  [163 158 162 255]
  [167 158 160 255]
  ...
  [115 110 114 255]
  [115 111 112 255]
  [114 110 111 255]]

 [[164 160 161 255]
  [163 159 160 255]
  [166 159 160 255]
  ...
  [115 111 112 255]
  [115 111 112 255]
  [114 110 111 255]]

 [[166 160 158 255]
  [170 164 162 255]
  [170 164 162 255]
  ...
  [113 109 110 255]
  [114 110 111 255]
  [114 110 111 255]]

 ...

 [[ 32  23  25 255]
  [ 31  22  24 255]
  [ 29  16  23 255]
  ...
  [  8  15  19 255]
  [  8  14  21 255]
  [  9  15  22 255]]

 [[ 31  22  24 255]
  [ 31  22  24 255]
  [ 27  17  22 255]
  ...
  [  8  13  22 255]
  [  8  11  19 255]
  [ 10  13  21 255]]

 [[ 31  22  23 255]
  [ 31  22  23 255]
  [ 34  26  24 255]
  ...
  [  8  13  24 255]
  [  8  11  19 255]
  [ 10  13  21 255]]]


Speed: 10.0ms preprocess, 175.1ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 174.0ms


[[[171 157 160 255]
  [171 157 160 255]
  [172 157 163 255]
  ...
  [116 106 124 255]
  [114 109 125 255]
  [109 104 120 255]]

 [[172 158 161 255]
  [172 158 161 255]
  [171 157 160 255]
  ...
  [116 107 123 255]
  [114 110 123 255]
  [110 106 119 255]]

 [[172 158 160 255]
  [170 156 158 255]
  [171 157 159 255]
  ...
  [117 111 124 255]
  [117 111 124 255]
  [111 105 118 255]]

 ...

 [[ 29  14  26 255]
  [ 26  11  23 255]
  [ 23   9  19 255]
  ...
  [ 18  13  22 255]
  [ 19  12  21 255]
  [ 19  12  21 255]]

 [[ 30  18  23 255]
  [ 26  14  19 255]
  [ 23  11  16 255]
  ...
  [ 18  13  22 255]
  [ 19  12  21 255]
  [ 20  13  22 255]]

 [[ 34  20  23 255]
  [ 28  14  17 255]
  [ 24  10  12 255]
  ...
  [ 20  13  22 255]
  [ 19  12  21 255]
  [ 20  13  22 255]]]


Speed: 0.0ms preprocess, 174.0ms inference, 16.1ms postprocess per image at shape (1, 3, 480, 640)



[[[131 120 134 255]
  [129 118 132 255]
  [131 118 137 255]
  ...
  [ 95  90  99 255]
  [ 95  92 101 255]
  [ 97  94 103 255]]

 [[129 121 132 255]
  [127 119 130 255]
  [131 120 134 255]
  ...
  [ 90  90 100 255]
  [ 93  94 102 255]
  [ 93  94 102 255]]

 [[128 123 132 255]
  [126 121 130 255]
  [126 120 131 255]
  ...
  [ 86  91 100 255]
  [ 91  94 102 255]
  [ 91  94 102 255]]

 ...

 [[249 255 254 255]
  [249 255 254 255]
  [249 255 254 255]
  ...
  [ 11  12  27 255]
  [ 10  12  22 255]
  [ 10  12  22 255]]

 [[249 255 254 255]
  [249 255 254 255]
  [249 255 254 255]
  ...
  [ 13  13  25 255]
  [ 13  13  23 255]
  [ 13  13  23 255]]

 [[249 255 254 255]
  [249 255 254 255]
  [249 255 254 255]
  ...
  [ 12  12  24 255]
  [ 12  12  22 255]
  [ 12  12  22 255]]]


0: 480x640 (no detections), 197.3ms
Speed: 15.6ms preprocess, 197.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 2 persons, 190.4ms


[[[102  81  99 255]
  [105  84 102 255]
  [102  82  97 255]
  ...
  [120  82  48 255]
  [117  80  51 255]
  [118  81  52 255]]

 [[103  80  96 255]
  [107  84 100 255]
  [102  82  97 255]
  ...
  [117  82  46 255]
  [117  80  49 255]
  [118  81  50 255]]

 [[103  79  98 255]
  [105  81 100 255]
  [105  82  98 255]
  ...
  [116  81  45 255]
  [117  80  51 255]
  [117  80  51 255]]

 ...

 [[ 45  34  21 255]
  [ 44  33  20 255]
  [ 46  29  26 255]
  ...
  [ 85  67  41 255]
  [ 82  65  42 255]
  [ 80  63  40 255]]

 [[ 45  34  21 255]
  [ 45  34  21 255]
  [ 47  29  29 255]
  ...
  [ 81  64  43 255]
  [ 80  63  42 255]
  [ 80  63  42 255]]

 [[ 47  36  25 255]
  [ 47  36  25 255]
  [ 45  27  27 255]
  ...
  [ 78  63  43 255]
  [ 77  62  42 255]
  [ 79  64  44 255]]]


Speed: 0.0ms preprocess, 190.4ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[[[ 96  97 112 255]
  [ 96  97 112 255]
  [ 96  98 108 255]
  ...
  [112  99  66 255]
  [117  97  63 255]
  [116  96  62 255]]

 [[ 95  96 111 255]
  [ 97  98 113 255]
  [ 96  98 108 255]
  ...
  [113  98  65 255]
  [117  97  63 255]
  [116  96  62 255]]

 [[ 95  97 109 255]
  [100 102 114 255]
  [ 96  98 108 255]
  ...
  [112  93  63 255]
  [112  92  60 255]
  [115  95  63 255]]

 ...

 [[ 50  29  33 255]
  [ 51  30  34 255]
  [ 48  27  31 255]
  ...
  [ 82  68  58 255]
  [ 80  68  59 255]
  [ 81  69  60 255]]

 [[ 54  31  34 255]
  [ 56  33  36 255]
  [ 49  26  30 255]
  ...
  [ 80  65  57 255]
  [ 78  61  58 255]
  [ 82  65  62 255]]

 [[ 52  31  28 255]
  [ 54  33  30 255]
  [ 53  28  29 255]
  ...
  [ 80  62  57 255]
  [ 79  60  57 255]
  [ 82  63  60 255]]]


0: 480x640 1 person, 1 cat, 193.7ms
Speed: 0.0ms preprocess, 193.7ms inference, 12.5ms postprocess per image at shape (1, 3, 480, 640)
